### ISSUE TITLE
slowness calculating counts of works for subgroups in group/show

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#36] opened 2011-08-24 20:57 UTC
The Sub-Groups box in groups/show does this
(#{g.works.size})

The groups works method in group.rb is doing this and it's extremely slow.
def works
    # @TODO: Do this the Rails way.
    self.people.collect { |p| p.works.verified }.uniq.flatten
  end

If you have a group with 40 sub-groups and lots of works, it will take the group view minutes to load.
1. The .verified scope appears to be the main bottleneck. Doesn't the works-person association only return verified contributorships anyway?
2. The verified method(scope?) returns duplicate work_ids which I assume is why .uniq is needed? By itself, works returns unique work_ids and seems to be acceptably fast, e.g. 
    self.people.collect { |p| p.works }

Is there still a need to use .verified in this case?
Is there a better way to do an association between Group and Work?
Sunspot should make this easy to get from Solr.

**Comment by jstirnaman** [comment] 2011-08-24 21:23
Ignore what I said about it being faster without .verified. It might be a little, but it's still really slow. I think I was comparing the wrong methods.

**Comment by jstirnaman** [comment] 2011-08-25 18:03
I switched over to Solr for this. Could probably be better still, but a huge improvement.
Replaced
(#{g.works.size})
with
= "(#{Index.fetch('_:_',["group_id:#{g.id}"],'score','desc',0,0,1).first.data['response']['numFound']})"

**Comment by hading** [comment] 2011-08-25 19:58
At first glance, yes, this does seem to be doing a lot of database work. 

I don't really love the solr solution as a permanent one just because it's kind of hard to tell what it's doing just by reading it. 

I'll see if I can come up with a candidate for replacing some of this that might work better than what's in there now. It ought to be possible to make the group.works method more efficient than that.

**Comment by hading** [comment] 2011-08-25 20:08
It should be possible to do this more efficiently from the database. Just a matter of coming up with the way and getting through all the relations properly.

**Comment by hading** [comment] 2011-08-25 20:24
We want something like the following I think, although this exact form doesn't give the same answer as the current implementation, so I'm trying to work out where the problem is. I think there's at least a chance that the current implementation is actually doing the wrong thing, so I want to check that too.

Work.verified.joins(:contributorships => {:person => :memberships}).where(:contributorships => {:person => {:memberships => {:group_id  => 23}}}).count

**Comment by hading** [comment] 2011-08-25 20:28
Interesting. With my development data for the largest group I get:

g.works.count = 2482
g.works.uniq.count = 1074
result of the above expression = 1467

Something is wrong somewhere.

**Comment by hading** [comment] 2011-08-25 20:29
Okay, one problem is that flatten should be called before uniq - otherwise we're only uniq'ing away arrays that are exactly the same, not individual works that are the same.

**Comment by hading** [comment] 2011-08-25 20:30
Okay, with that change g.works.count and g.works.uniq.count are the same, as one would expect.

**Comment by jstirnaman** [comment] 2011-08-25 20:30
> It ought to be possible to make the group.works method more efficient than
> that.

I thought so too. Is it possible to build a closer association between
groups and works, or use an include?

I don't really love the solr solution as a permanent one

I don't love _my_ solr solution, but in general I love solr as the solution.
I have been working with Sunspot lately and really like the "black box", as
you put it.

**Comment by hading** [comment] 2011-08-25 20:32
Yeah, at the right point in time a solr solution might be all right. But the one with the current implementation of solr is impenetrable. If you're following the issue you'll see I'm working on a query solution. I'm just not sure why it's giving a different answer.

**Comment by jstirnaman** [comment] 2011-08-25 20:34
I started to do something like that, but was fuzzy on how to do the :person
=> , making sure that we're only getting counts for people and not any
contributorships.

**Comment by hading** [comment] 2011-08-25 20:37
What is happening is that multiple contributorships are causing an inflated count. Since using 'count' just does a COUNT(*) directly in the SQL query this doesn't get resolved.

If you actually instantiate the works from this query and then uniq them you get the right answer. So I need to see if the query can be modified to do that for me. Of course, I'd rather not have to instantiate all of the works just to get a count.

**Comment by hading** [comment] 2011-08-25 20:40
Yeah, a little bit frustrating that it would be easy to write the SQL to do this, but I'm not sure offhand how to force Rails/AREL  to do it correctly.

**Comment by hading** [comment] 2011-08-25 20:52
At:

http://guides.rubyonrails.org/active_record_querying.html

in the Calculations section there is actually the hint giving the answer. It makes a difference whether one uses joins or includes. With joins you see to get a SELECT COUNT(whatever) and with includes you get a SELECT COUNT(DISTINCT whatever). 

So what we need is something like:

Work.verified.includes(:contributorships => {:person => :memberships}).where(:contributorships => {:person => {:memberships => {:group_id => 23}}}).count

Of course, we want to just use the first part to return a still-chainable query and only in the actual view hit it with count (instead of size, which I think would cause instantiation of all the works and then a count on the array. Or it might just toss an error.)

**Comment by hading** [comment] 2011-08-25 21:07
All right. A fix is in commit 03012b83. 

Jason - if you wouldn't mind trying it this way and letting me know if it fixes the speed problem I'd appreciate it. Even the larger groups I'm trying here aren't even all that slow on the old system.

**Closed as completed by hading** 2011-08-25 21:07 UTC
