### ISSUE TITLE
Duplicate works not detected during import

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#88] opened 2012-02-28 17:38 UTC
Duplicate works aren't being detected during a batch import.
Code version: BibApp/master
Steps:
1. Import a work for a person.
2. Import the same work for the same person again.
Result: Second work does not get flagged as a duplicate.

Possibility related to the fix for https://github.com/BibApp/BibApp/issues/48 ?

**Comment by jstirnaman** [comment] 2012-02-28 18:04
Hmmm... Index.possible_accepted_duplicate_works(w2) returns expected results, but there are no results at all for this work at /admin/duplicates#index

**Comment by jstirnaman** [comment] 2012-02-28 18:18
I guess that makes sense since the imports have already been accepted. I need to focus on just the import process.

**Comment by jstirnaman** [comment] 2012-02-28 18:47
I'm questioning whether
     AND (#{Work.solr_duplicate_filter})

should be in query_params for Index.possible_unaccepted_duplicate_works. 

Or, maybe the work is getting accepted too soon? On import#show, the work displays as "Accepted", but the import hasn't been accepted yet (separate issue, but that's confusing from a user perspective.)

Assuming w1 is existing accepted work and w2 is newly imported duplicate work, here's what I get before removing the status filter:
Index.possible_unaccepted_duplicate_works(w1) returns []
Index.possible_accepted_duplicate_works(w2) returns all the accepted works that I'd expect.

Removing the status filter from .possible_unaccepted_duplicate_works returns works that I'd expect it to.

**Comment by hading** [comment] 2012-03-08 22:31
Introduction of this method and filter seems to have occured around commit a6342a3.

**Comment by hading** [comment] 2012-03-08 22:34
It is possible that the problem sits around the notion of a work being accepted and that of an import being accepted and those two things not being related in a natural seeming way. At least I seem to remember looking at something else (perhaps the aforementioned issue) and believing that something was going on there. Let me poke around in that again.

**Comment by hading** [comment] 2012-03-08 22:45
Just some data about how this works:

Before a work is saved deduplicate is called. It's worth noting that in the distant past this was called after saves through an observer. It's possible that it matters and moving it to after_save would help.

deduplicate uses Index.possible_accepted_duplicate_works(self) to get a list of possible duplicate works. If the list is empty then the work is accepted. So what being accepted means is that no duplicates were found before saving the object.

If this is a non-accepted work with potential accepted dupe_candidates then it is marked as a duplicate.

It is conceivable to me that when I moved this from after save to before save it may have interfered with the generation of the candidate list, although I don't necessarily think so. I'll try moving it back to see if that affects anything related to this issue.

**Comment by hading** [comment] 2012-03-08 23:05
As I feared, moving it into after save potentially produces a loop. I don't know if there's a good way to break that. I'm going to try the obvious.

**Comment by hading** [comment] 2012-03-08 23:06
Trying the obvious doesn't seem to affect anything. 

As an aside, I really kind of hate running this process through solr. Is it not possible to detect all of this stuff directly in the database in a reasonably efficient manner?

**Comment by hading** [comment] 2012-03-08 23:15
Note that possible_unaccepted_duplicate_works only seems to be used in WorksController::destroy, so I'm not sure that it could have anything to do with this problem.

In turn, possible_accepted_duplicate_works is only used by Work#deduplicate - I think it's here that the problem must lie.

The good news is that since these are each only used once, we can modify them to our heart's content, or feel pretty free in replacing them. 

I may need to take a look at solr directly to see what is happening.

**Comment by hading** [comment] 2012-03-08 23:16
I hadn't noticed, but my change running deduplicate after instead of before _did_ keep the second one from becoming accepted, although it still doesn't show up as duplicate. That may be progress.

**Comment by hading** [comment] 2012-03-08 23:26
Now if I run deduplicate manually on my second import it _does_ correctly become and show as a duplicate. So the problem now is to figure out how to get the stuff to run correctly without any loops or such. The problem is that the create_contributorships method also runs in after save with special handling, so we need to make sure that all of that happens correctly and no loop is possible. 

The create_contributorships handling is that when we create through the controller WorksController::create then we want to run create_contributorships. When we are running an import then we want to skip running it. (In both cases it goes through Work.create_from_hash, which has a parameter to tell whether to run that part of the after callback.).  In the second case create_contributorships is called manually if and only if the import is accepted.

However, we _do_ need to call deduplicate right away, as that is what will determine if the work is a duplicate or is accepted. However, that call to deduplicate cannot be allowed to trigger create_contributorships.

We then also need to work things for a normal save. A problem is that deduplicate potentially affects the state of work itself (unlike create_contributorships), so may require new data to be saved. In this case we should either bypass the callbacks when doing this (by using a direct update method) or _always_ make deduplicate bypass the after callbacks (whereas create_contributorships just needs to bypass itself, not deduplicate.

I think that from all of that I see how I can fix this, but I won't get to it until tomorrow.

**Comment by hading** [comment] 2012-03-09 16:51
I have a fix in. Move deduplicate to an after_save and arrange so that it doesn't itself trigger any after_save callbacks. This seems to resolve the case mentioned when this issue was opened.

**Closed as completed by hading** 2012-03-09 16:51 UTC
Labels: importing-works
