### ISSUE TITLE
Duplicates created during batch upload

### ISSUE THREAD

**Issue by jfurfey** [BibApp/BibApp#48] opened 2011-10-31 15:58 UTC
We just updated to the trunk version.  All appeared fine the last
couple of days.

Just tried a batch load of works.  Only 7 citations in Refworks XML
format.  No errors during the batch process, but the results screen
shows all works have duplicate records.  Upon further review, the dups
are there because during the add batch process each work was created 4
times.

I have been able to duplicate this bug.

Anyone seen this or have any ideas on what my be causing it?

**Comment by cjuergen** [comment] 2011-11-03 15:28
Can confirm this on the i18n branch.
Seems as if the citations in the import are directly accepted and duplicated while the import is processed. 
E.g.: an import with 1 citation (not yet in the system)
Import - status reviewable
The admin import page (users/1/imports/11) where you can accept or reject the import shows the import as containing
0 works
1 duplicate

Person manage contributorships (contributorships?person_id=2) shows
1 work to manage

Admin - orphaned works ( works/orphans) shows
2 orphans matching the title in the import

Admin - show duplicates (admin/duplicates) shows
4 works
2 accepted and 2 duplicates

After having viewed the duplicates the list of orphaned works shows the title 4 times and back to duplicates there are 8 now.

Looking at the database, directly after the import is processed the works table shows 2 entries for the imported work.
1 with the work_state_id 3 the others with work_state_id 2
After selecting the batch import for review, the work table shows 3 entries for the work.
After selecting view orphaned works the work table shows 4 entries for the work.

This might be related to Issue 49 https://github.com/BibApp/BibApp/issues/49

**Comment by cjuergen** [comment] 2011-11-03 16:21
It seems as if the import is processed several times.

delayed_job.log
2011-11-03T17:06:02+0100: [Worker(delayed_job host:vmx012 pid:25830)] Import#batch_import failed with AASM::InvalidTransition: Event 'review' cannot transition from 'reviewable' - 1 failed attempts
2011-11-03T17:06:02+0100: [Worker(delayed_job host:vmx012 pid:25830)] 1 jobs processed at 3.0701 j/s, 1 failed ...
2011-11-03T17:06:28+0100: [Worker(delayed_job host:vmx012 pid:25830)] Import#batch_import failed with AASM::InvalidTransition: Event 'review' cannot transition from 'reviewable' - 2 failed attempts
2011-11-03T17:06:28+0100: [Worker(delayed_job host:vmx012 pid:25830)] 1 jobs processed at 1.8192 j/s, 1 failed ...
2011-11-03T17:07:58+0100: [Worker(delayed_job host:vmx012 pid:25830)] Import#batch_import failed with AASM::InvalidTransition: Event 'review' cannot transition from 'reviewable' - 3 failed attempts
2011-11-03T17:07:58+0100: [Worker(delayed_job host:vmx012 pid:25830)] 1 jobs processed at 3.0599 j/s, 1 failed ...

In the database the import processed produced several works, note the works_added
bibapp_development_cj=> select \* from imports where id=17;
 id | user_id | person_id |   state    | works_added | import_errors |         created_at         |         updated_at  
----+---------+-----------+------------+-------------+---------------+----------------------------+----------------------------
 17 |       1 |         2 | reviewable | ---         | --- {}        | 2011-11-03 16:05:51.895439 | 2011-11-03 16:07:58.858337
                                       : - 2296      :  
                                       :             :  
(1 row)

bibapp_development_cj=> select \* from imports where id=17;
 id | user_id | person_id |   state    | works_added | import_errors |         created_at         |         updated_at  
----+---------+-----------+------------+-------------+---------------+----------------------------+----------------------------
 17 |       1 |         2 | reviewable | ---         | --- {}        | 2011-11-03 16:05:51.895439 | 2011-11-03 16:12:24.668084
                                       : - 2298      :  
                                       :             :

**Comment by hading** [comment] 2011-11-08 22:15
commit 5c23d566668fe9878b200b195ddbf75b7969d19f is a stab at a dirty fix to this

It should prevent batch_import from trying to run when the import is in the wrong state.
I don't know if it will fix the generation of multiple works, but it has a shot - if multiple batch_imports are run in with the import in the 'processing' state I think that transactions will force all but possibly one of them to fail, rolling back extra created works. I'm not sure of this though (I still can't reproduce this locally). 

I'm still not sure why batch_import might try to run more than once.

We'll see if this change does anything for John or Claudia and reassess at that point.

**Comment by cjuergen** [comment] 2011-11-09 13:51
Hello Howard,

just tried the import on master and it works partially. No errors occur and thus the delayed job isn't retried.  Email notification about import being ready for review is sent.

The works created still got the status accepted prior to the import beiing accepted. Thus an editor or administrator can verify the contributorship prior to the import itself being accepted.

Claudia

**Comment by hading** [comment] 2011-11-09 16:30
Hi Claudia,

Is the import in question for a specific person (i.e. view a person, Add 
Works, upload a file, etc.) or a general upload (Admin, Works, Add 
Works, upload a file, etc.)? In the former case we (at the request of 
people here at UIUC) auto-accept the associated works (though maybe it 
could be arranged to happen after acceptance).

I acknowledge that this might be a problem in any case, but before 
addressing that I want to know whether it is behaving as expected (to 
me) or if there is something I don't understand happening.

Thanks,
Howard

**Comment by cjuergen** [comment] 2011-11-09 16:47
I tried it with both variations
- import for a specific person
- system import
  In both cases the created works were associated with a person matching the author name. The contributorship was manageable via both ways person - manage contributorships, admin - manage contributorships before the import was accepted.

Claudia

**Comment by hading** [comment] 2011-11-09 18:04
Okay, I'll have a closer look at the accepted problem.

Regarding the notifier error in i18n - the problem here is that the 
notifier is trying to create an URL in the email, but it doesn't have a 
locale. This is probably a general problem when calling a mailer from 
delayed_job. If they're getting called through a controller action then 
a locale is available and (I believe) used - since you've reported the 
other mailers are working (with proper localization, I assume) I won't 
worry about those.

I guess the solution here is to store the locale that is active when the 
import is created (in the Import object) and use that to reset the 
locale and generate the url when delayed job sends the notice.

Howard

**Comment by hading** [comment] 2011-11-09 18:30
Actually perhaps a better solution to the notifier email is just to go 
ahead and implement a user selectable locale (i.e. attached to the User) 
and then to present the email in that locale. We want that eventually 
anyway and it would avoid having to add something of otherwise 
questionable value to Import.

I think I'll do that. I may not immediately use it in all the places 
where it is appropriate, but will at least for the Import and perhaps 
for setting the locale in Application controller.

Howard

**Comment by hading** [comment] 2011-11-10 16:48
Hi Claudia,

I think I know what is happening with this and I think there's an easy 
way to fix it. Will investigate further.

Also I think I fixed the notifier mailing problem when an import becomes 
reviewable in i18n. Along the way I added the ability for a user to have 
a default locale (which is used in some circumstances by 
ApplicationController to set the locale and will automatically be used 
when a user logs in - although they can still change the locale they're 
actually seeing after that by using the picker).

Howard

**Comment by hading** [comment] 2011-11-10 21:52
I'm waiting to see if this has fixed things for jfurfey - I still haven't managed to replicate.

**Comment by jfurfey** [comment] 2011-11-10 21:59
Howard. Sorry for not replying sooner. I am on the road and won't be able to test the changes until Monday. Thanks for taking a look so quickly.

**Comment by hading** [comment] 2011-11-10 22:01
Hi,

That's fine. Claudia reports it is fixed for her, so I'm hopeful. Let me 
know when you have a chance.

Howard

**Comment by jfurfey** [comment] 2011-12-05 20:37
This is now fixed for us as well.  Thanks.

**Comment by hading** [comment] 2011-12-05 20:39
Okay, closing then.

**Closed as completed by hading** 2011-12-05 20:39 UTC
